### ISSUE TITLE
-_

### ISSUE THREAD

**Issue by iandoug** [NickG13/AEIOU#1]
Hi

Where are - _ and mdash? Hard to tell apart :-)

Or do you maybe have both versions of KLA json?  Only got up to second last key in top row of ISO.

Thanks, Ian

**Comment by NickG13** [comment]
Hi Ian! Thank you for showing up around my experiment! 
I will tell you where are they, QWERTY = AEIOU
6 = - (6 base key)
" = _ (2 + shift)

I don't remember adding mdash, but it's a legit option for writers tbh.

**Comment by iandoug** [comment]
What's on the / key (3rd last in top row) ?

Thanks, Ian

**Comment by NickG13** [comment]
Sorry for the delay Ian. 
In the / key there is \ and %, I don't understand if that's what you are asking. 
I close because the original doubt is solved
