### ISSUE TITLE
instalacion en windows10

### ISSUE THREAD

**Issue by edugit** [NickG13/AEIOU#3]
Estoy muy interesado en probar su layout de "teclado en llamas" pero estoy teniendo muchas dificultades en instalarla
al abrir el archivo zip de "teclado en llamasbunble" encuentro archivos con extension .icnc, y. layout.
podria elaborar un poco mas como se instalan en windows10.

Sería posible al menos conseguir un screenshot del layout para poder 
 " fabricarlo" en Microsoft Keyboard Layout Creator (MSKLC) ?
disculpe las molestias, gracias

I am very interested in trying out your "teclado en llamas" layout, but I am having a lot of difficulty installing it. When I open the "teclado en llamamas  Bundle" zip file, I find files with the extensions .icnc and .layout. Could you provide a bit more detail on how to install them on Windows 10? Sorry for the inconvenience, thank you.

**Comment by NickG13** [comment]
Aquí lo tienes hecho. La anterior versión era solo para Mac.  No tengo problemas en pasar screenshots, pero mejor pasarlo ;) 
También está ya en la página principal 
https://github.com/NickG13/AEIOU/files/11263146/Teclado.en.Llamas.Windows.zip
